listen_address=http://0.0.0.0:88
log_level=debug

web_directory=/var/www/aquachemd

mqtt_server = mqtt://homeassistantdev:1883
mqtt_user = system
mqtt_passwd = bollocks

mqtt_aquachemd_topic= aquachemd
mqtt_aqualinkd_topic= aqualinkd
#mqtt_discovery_topic=
#mqtt_server=
#mqtt_user=
#mqtt_passwd=
mqtt_discovery_use_mac=YES
mqtt_convert_to_degF=NO
mqtt_timed_update=YES

sensor_poll_time=10

