#main_label=Sampling

listen_address=http://0.0.0.0:88
log_level=notice

web_directory=/var/www/aquachemd

#mqtt_server = mqtt://homeassistant:1883
#mqtt_user = 
#mqtt_passwd = 
mqtt_aquachemd_topic= aquachemd
mqtt_aqualinkd_topic= aqualinkd
#mqtt_discovery_topic=
#mqtt_server=
#mqtt_user=
#mqtt_passwd=
mqtt_discovery_use_mac=YES
mqtt_convert_to_degF=NO
mqtt_timed_update=YES

gpio_chip=/dev/gpiochip0

sensor_poll_time=10

temp_compensated_ph=yes

temp_sensor_label=Flow Cell Temperature
temp_sensor_type=ezo
temp_sensor_address=0x68
temp_sensor_scope_global=true

ph_sensor_label=pH
ph_sensor_type=ezo
ph_sensor_address=0x63
ph_sensor_scope_global=true
ph_sensor_statistics=1w

orp_sensor_label=ORP
orp_sensor_type=ezo
orp_sensor_address=0x64
orp_sensor_scope_global=true
orp_sensor_statistics=1d

gpio_doser_label=Acid doser
gpio_doser_type=pH
gpio_doser_pin=19
gpio_doser_pin_mode=Active High
gpio_doser_required_state=on
gpio_doser_ml_per_second=2.180000

