#main_label=Sampling

listen_address=http://0.0.0.0:88
log_level=notice

web_directory=/var/www/aquachemd

#mqtt_server = mqtt://homeassistant:1883
#mqtt_user = 
#mqtt_passwd = 
mqtt_aquachemd_topic= aquachemd
mqtt_aqualinkd_topic= aqualinkd
#mqtt_discovery_topic=
#mqtt_server=
#mqtt_user=
#mqtt_passwd=
mqtt_discovery_use_mac=YES
mqtt_convert_to_degF=NO
mqtt_timed_update=YES

gpio_chip=/dev/gpiochip0

sensor_poll_time=10

temp_compensated_ph=yes


# xxxx_label has to be first line of any condition or sensor

#mqtt_condition_label=AqualinkD Alive
#mqtt_condition_topic=aqualinkd/Alive
#mqtt_condition_value=1

mqtt_condition_label=Pump
mqtt_condition_topic=aqualinkd/Filter_Pump
mqtt_condition_value=1

mqtt_condition_label=SWG Flow
mqtt_condition_topic=aqualinkd/SWG/fullstatus
mqtt_condition_value=0

gpio_condition_label=Flow Cell Level Sensor
gpio_condition_pin=18
gpio_condition_pin_mode=active_high
gpio_condition_required_state=on


temp_sensor_label=Flow Cell Temperature
temp_sensor_type=ezo
temp_sensor_address=0x68

ph_sensor_label=pH
ph_sensor_type=ezo
ph_sensor_address=0x63

orp_sensor_label=ORP
orp_sensor_type=ezo
orp_sensor_address=0x64

#temp_sensor_label=Pool Temp
#temp_sensor_type=mqtt
#temp_sensor_topic=aqualinkd/Temperature/Pool

#temp_sensor_type=d1w
#temp_sensor_path=/sys/bus/w1/devices/28-000006c3b7a0/w1_slave

# Example dosers
doser_label=Acid doser
doser_type=gpio
doser_pin=16
doser_pin_mode=active_low
doser_required_state=on

doser_label=Chlorine doser
doser_type=ezo
doser_address=0x64