#main_label=Sampling

listen_address=http://0.0.0.0:88
log_level=notice

web_directory=/var/www/aquachemd

mqtt_aquachemd_topic= aquachemd
mqtt_aqualinkd_topic= aqualinkd

gpio_chip=/dev/gpiochip0

sensor_poll_time=5


ph_dose_range=8.0:50
ph_dose_range=7.8:20
ph_dose_range=7.7:10
ph_dose_range=7.6:5
ph_dose_range=7.5:0

temp_compensated_ph=no

#temp_sensor_label=Flow Cell Temperature
#temp_sensor_type=ezo
#temp_sensor_address=0x68

ph_sensor_label=pH
ph_sensor_type=ezo
ph_sensor_address=0x63

orp_sensor_label=ORP
orp_sensor_type=ezo
orp_sensor_address=0x64

sysfs_sensor_label=CPU Temp
sysfs_sensor_path=/sys/class/thermal/thermal_zone0/temp
sysfs_sensor_offset=0
sysfs_sensor_scale=0.001
sysfs_sensor_uom=celsius



